#!/bin/bash
# cross_dialog_ack_sweep.sh v0.1 · L1 of cross-dialog ACK protocol
#
# Find handoff files with `ack_required: true` in given memory dir, write ack
# stub for each not already acked. Run at session-start to ensure inbound
# handoffs don't get silently dropped (root cause of 5/22 + 5/23 18h info loss).
#
# Usage:
#   cross_dialog_ack_sweep.sh [<memory_dir>]
#
# Default memory_dir: ~/.claude/projects/$(basename $PWD | tr / -)/memory
#
# Exit codes:
#   0 = sweep done (may have written 0 or N ack stubs)
#   1 = memory dir missing
#
# Stub format: see SPEC memory/spec_cross_dialog_ack_protocol_v01.md §4

set -e
set -o pipefail

MEM_DIR="${1:-$HOME/.claude/projects/$(basename "$PWD" | tr / -)/memory}"

[ -d "$MEM_DIR" ] || { echo "FAIL: memory dir not found: $MEM_DIR"; exit 1; }

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
ACKED=0
SKIPPED=0
EXPIRED=0

# use find with mtime limit · memory dir can have 20k+ session files
# (auto cycle dumps · etc) · bash glob would explode ARG_MAX
SWEEP_DAYS="${SWEEP_DAYS:-30}"
while IFS= read -r -d '' f; do
  # filter by ack_required: true (handles both session_*handoff* and other session formats)
  grep -qE "^  ack_required: true$" "$f" 2>/dev/null || continue

  base=$(basename "$f" .md)
  ack_file="$MEM_DIR/ack_${base}.md"

  # already acked? skip
  if [ -f "$ack_file" ]; then
    SKIPPED=$((SKIPPED+1))
    continue
  fi

  # check deadline expired (informational)
  deadline=$(grep -E "^  ack_deadline:" "$f" 2>/dev/null | sed 's/.*ack_deadline:[[:space:]]*//' | tr -d '"' | head -1)
  if [ -n "$deadline" ]; then
    # use python for ISO8601 compare (portable across OS)
    EXPIRED_FLAG=$(python3 -c "
import sys, datetime
try:
    dl = datetime.datetime.fromisoformat('$deadline'.replace('Z', '+00:00'))
    now = datetime.datetime.now(datetime.timezone.utc)
    sys.exit(0 if now > dl else 1)
" 2>/dev/null && echo "yes" || echo "no")
    [ "$EXPIRED_FLAG" = "yes" ] && EXPIRED=$((EXPIRED+1))
  fi

  # extract topic from handoff for ack header
  topic=$(grep -E "^description:" "$f" 2>/dev/null | sed 's/^description:[[:space:]]*//' | head -1 | cut -c 1-100)

  # write ack stub
  cat > "$ack_file" <<EOF
---
name: ack-${base}
description: "ack for ${base} · auto-generated by cross_dialog_ack_sweep · please update status + plan"
metadata:
  node_type: memory
  type: ack
  ack_for: ${base}
  ack_at: ${NOW}
  ack_status: received
  ack_eta: null
  ack_note: "auto-stub · pending manual review + plan"
  acked_by_agent: $(whoami)@$(hostname)
---

# Ack for [[${base}]]

## Status: received (auto-stub)

This ack was auto-generated by \`cross_dialog_ack_sweep.sh\` at session-start.

**Original handoff topic**: ${topic}

## TODO before close

- [ ] Update \`ack_status\`: received → in_progress | done | declined
- [ ] Fill \`ack_eta\` if accepting (ISO8601)
- [ ] Fill \`ack_note\` with decision + plan
- [ ] When done · grep handoff acceptance criteria · verify ship + update status=done
EOF

  ACKED=$((ACKED+1))
  echo "ACKED: $base"
done < <(find "$MEM_DIR" -maxdepth 1 -name 'session_*.md' -mtime "-${SWEEP_DAYS}" -print0)

echo ""
echo "sweep done: $ACKED new ack | $SKIPPED already acked | $EXPIRED past deadline (scope: ${SWEEP_DAYS}d)"
exit 0
