"""v1.7.1 · S_GBrain module 4 · skill_cron_emitter · crontab line generation.

Reads cron_schedule from SKILL.md frontmatter · emits crontab-compatible line
plus a wrapper shell script that invokes the skill handler.

Validates crontab syntax (strict regex · rejects shell metachars).
NO LLM. Pure template generation.

Reference: paper/SPEC_GBRAIN_SKILLPACK_REWRITE.md section 4.4 row 4.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

try:
    from .skill_loader import parse_skill_md
except (ImportError, ValueError):
    from skills_pkg.skill_loader import parse_skill_md  # type: ignore

# Conservative crontab pattern · 5 fields (m h dom mon dow) · only digits/*/,/-//
# Rejects shell metacharacters (; & | $ ` etc)
CRONTAB_FIELD_RE = re.compile(r"^[\d\*\,\-\/]+$")


def validate_crontab(schedule: str) -> bool:
    """Validate crontab schedule string · 5 fields · safe chars only."""
    if not isinstance(schedule, str):
        return False
    schedule = schedule.strip()
    if not schedule:
        return False
    fields = schedule.split()
    if len(fields) != 5:
        return False
    return all(CRONTAB_FIELD_RE.match(f) for f in fields)


def emit_cron_script(skill_dir: Path, schedule: str,
                     output_dir: Optional[Path] = None) -> Optional[Path]:
    """Write wrapper shell script that invokes skill via Python.

    Returns script path or None if schedule invalid.
    """
    if not validate_crontab(schedule):
        return None
    if not isinstance(skill_dir, Path):
        skill_dir = Path(skill_dir)
    if output_dir is None:
        output_dir = skill_dir.parent.parent.parent / "cron"
    if not isinstance(output_dir, Path):
        output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    handler_path = skill_dir / "handler.py"
    script_lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by compass skill_cron_emitter · DO NOT EDIT",
        f"# Skill: {skill_dir.name}",
        f"# Schedule: {schedule}",
        "set -euo pipefail",
        f"cd \"{skill_dir.parent.parent.parent.resolve()}\"",
        f"python3 -c \"import sys; sys.path.insert(0, '.'); "
        f"from skills_pkg.skill_loader import load_handler; "
        f"from pathlib import Path; "
        f"fn = load_handler(Path('{skill_dir}'), Path('{skill_dir.parent.parent}')); "
        f"print(fn({{}}, {{}}) if fn else 'no handler')\"",
    ]
    script_path = output_dir / f"skill_{skill_dir.name}_cron.sh"
    script_path.write_text("\n".join(script_lines) + "\n", encoding="utf-8")
    try:
        script_path.chmod(0o755)
    except (OSError, PermissionError):
        pass
    return script_path


def emit_crontab_line(skill_dir: Path, schedule: str,
                      output_dir: Optional[Path] = None) -> str:
    """Return one crontab line that invokes the wrapper script."""
    if not validate_crontab(schedule):
        return ""
    if not isinstance(skill_dir, Path):
        skill_dir = Path(skill_dir)
    if output_dir is None:
        output_dir = skill_dir.parent.parent.parent / "cron"
    script_path = output_dir / f"skill_{skill_dir.name}_cron.sh"
    return f"{schedule} {script_path.resolve()}"


def emit_for_skill(skill_dir: Path,
                   output_dir: Optional[Path] = None) -> dict:
    """One-shot · parse frontmatter · validate · emit script + crontab line."""
    if not isinstance(skill_dir, Path):
        skill_dir = Path(skill_dir)
    try:
        front = parse_skill_md(skill_dir)
    except Exception:
        return {"ok": False, "reason": "SKILL.md parse failed"}
    schedule = front.get("cron_schedule", "").strip()
    if not schedule or schedule.lower() in ("null", "none"):
        return {"ok": False, "reason": "no cron_schedule declared"}
    if not validate_crontab(schedule):
        return {"ok": False, "reason": f"invalid crontab syntax: {schedule!r}"}
    script_path = emit_cron_script(skill_dir, schedule, output_dir=output_dir)
    line = emit_crontab_line(skill_dir, schedule, output_dir=output_dir)
    return {"ok": True, "script_path": str(script_path) if script_path else "",
            "crontab_line": line, "schedule": schedule}
